export { default as vsButton } from './vsButton/Base/index'
export { default as vsButtonGroup } from './vsButton/group/index'
export { default as vsAlert } from './vsAlert/Base/index'
export { default as vsInput } from './vsInput/Base/index'
export { default as vsCheckbox } from './vsCheckbox/Base/index'
export { default as vsSwitch } from './vsSwitch/Base/index'
export { default as vsSelect } from './vsSelect/index'
export { default as vsOption } from './vsOption/index'
export { default as vsOptionGroup } from './vsOptionGroup/index'
export { default as vsList } from './vsList/index'
export { default as vsAvatar } from './vsAvatar/Base/index'
export { default as vsAvatarGroup } from './vsAvatar/Group'
export { default as vsRadio } from './vsRadio/Base/index'
export { default as vsTooltip } from './vsTooltip/Base/index'
export { default as vsDialog } from './vsDialog/Base/index'
export { default as vsPagination } from './vsPagination/Base/index'
export { default as vsTable } from './vsTable/Base/index'
export { default as vsTableTr } from './vsTable/Tr'
export { default as vsTableTh } from './vsTable/Th'
export { default as vsTableTd } from './vsTable/Td'
export { default as vsNavbar } from './vsNavbar/Base/index'
export { default as vsNavbarItem } from './vsNavbar/Item'
export { default as vsNavbarGroup } from './vsNavbar/Group'
export { default as vsSidebar } from './vsSidebar/Base/index'
export { default as vsSidebarItem } from './vsSidebar/Item'
export { default as vsSidebarGroup } from './vsSidebar/Group'
export { default as vsCard } from './vsCard/Base/index'
export { default as vsCardGroup } from './vsCard/Group'
export { default as vsAccordion } from './vsAccordion/Base/index'
export { default as vsTextarea } from './vsTextarea/Base/index'

// export { default as vsDropdown } from './vsDropdown/Base/index'
// new component slot
